<a href="https://colab.research.google.com/github/shyookml/sml/blob/ch2/sml_ch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 2: Ex.2-1
# SVD (Singular value decomposition)
Based on the definition of Singular value decomposition

In [1]:
import numpy as np
import numpy.linalg as nla

A=np.array([[1,1],[1,1],[-1,1]],float)
AT=np.transpose(A)

print("A=",A)
print("AT=",AT)

M=np.dot(AT,A)
eigval_M,eigvec_M=nla.eig(M)
V=np.copy(eigvec_M)
print("V=")
print(V)

M=np.dot(A,AT)
eigval_M,eigvec_M=nla.eig(M)
print("eigvec_M=",eigvec_M)
U=np.copy(eigvec_M)
print("U=")
print(U)

Sigma=np.dot(np.transpose(U),A)
Sigma=np.dot(Sigma,V)
print("Sigma=")
print(Sigma)
AA=np.dot(U,Sigma)
AA=np.dot(AA,np.transpose(V))
print("A=")
print(AA)

A= [[ 1.  1.]
 [ 1.  1.]
 [-1.  1.]]
AT= [[ 1.  1. -1.]
 [ 1.  1.  1.]]
V=
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
eigvec_M= [[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
U=
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
Sigma=
[[2.00000000e+00 4.47422863e-17]
 [3.14018492e-16 0.00000000e+00]
 [0.00000000e+00 1.41421356e+00]]
A=
[[ 1.  1.]
 [ 1.  1.]
 [-1.  1.]]


## Using svd function in numpy

In [2]:
import numpy as np
import numpy.linalg as nla
U,Sigma,V=nla.svd(A,full_matrices=True)
print("U=")
print(U)
print("V=")
print(V)
print("Sigma=")
print(Sigma)

U=
[[-7.07106781e-01 -4.02873103e-17  7.07106781e-01]
 [-7.07106781e-01 -2.66910636e-16 -7.07106781e-01]
 [ 1.12180787e-16 -1.00000000e+00  5.55111512e-17]]
V=
[[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]
Sigma=
[2.         1.41421356]


# define my own svd funcion

In [3]:
import numpy as np
import numpy.linalg as nla

def svd(A):
  AT=np.transpose(A)
  M=np.dot(AT,A)
  eigval_M,eigvec_M=nla.eig(M)
  idx=np.argsort(eigval_M)
  #idx=idx[::-1]
  eigval_M=eigval_M[idx]
  eigvec_M=eigvec_M[:,idx]

  V=np.copy(eigvec_M)

  M=np.dot(A,AT)
  eigval_M,eigvec_M=nla.eig(M)
  idx=np.argsort(eigval_M)
  #idx=idx[::-1]
  eigval_M=eigval_M[idx]
  eigvec_M=eigvec_M[:,idx]

  U=np.copy(eigvec_M)

  Sigma=np.dot(np.transpose(U),A)
  Sigma=np.dot(Sigma,V)

  return U,Sigma,V

In [4]:
A=np.array([[1,1],[1,1],[-1,1]],float)
U,Sigma,V=svd(A)
print("U=")
print(U)
print("Sigma=")
print(Sigma)
print("V=")
print(V)
print("")
print(np.dot(np.dot(U,Sigma),np.transpose(V)))

U=
[[-0.70710678  0.          0.70710678]
 [ 0.70710678  0.          0.70710678]
 [ 0.          1.          0.        ]]
Sigma=
[[0.00000000e+00 3.14018492e-16]
 [1.41421356e+00 0.00000000e+00]
 [4.47422863e-17 2.00000000e+00]]
V=
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]

[[ 1.  1.]
 [ 1.  1.]
 [-1.  1.]]


# CUR 분해

In [5]:
import numpy as np
import numpy.linalg as nla
import numpy.random as nr
A=np.array([[4,4,4,0,0],[2,2,2,0,0],[5,5,5,0,0],[1,1,1,0,0],[0,0,0,3,3],[0,0,0,4,4],[0,0,0,1,1]],float)
# print(A)
# print(A**2)

p=np.sum(A**2,axis=0)  # Frobenius norm을 이용한 확률
q=np.sum(A**2,axis=1)
p/=np.sum(p)
q/=np.sum(q)
print(p)
print(q)

r=2    # 뽑을 행/열의 갯수
col_list=nr.choice(np.array(range(len(p))),r,replace=False,p=p)
print(col_list)
row_list=nr.choice(np.array(range(len(q))),r,replace=False,p=q)
print(row_list)

# for ex 2-5 only
col_list[0]=1
col_list[1]=3
row_list[0]=0
row_list[1]=2

C=np.zeros([A.shape[0],r],float)
R=np.zeros([r,A.shape[1]],float)
for i in range(r):
  C[:,i]=A[:,col_list[i]]
  C[:,i]/=((r*p[col_list[i]])**0.5)
  R[i,:]=A[row_list[i],:]
  R[i,:]/=((r*q[row_list[i]])**0.5)
print("C=")
print(C)

print("R=")
print(R)

W=np.zeros([r,r],float)
for i in range(r):
  for j in range(r):
    W[i,j]=A[row_list[i],col_list[j]]
print("W=")
print(W)

X,Sigma,Y=svd(W)

print("\nX=")
print(X)
print("\nSigma=")
print(Sigma)
print("\nY=")
print(Y)
print("")
#print(np.dot(np.dot(X,Sigma),np.transpose(Y)))
InvSig=np.zeros_like(np.transpose(Sigma))
for i in range(Sigma.shape[0]):
  if abs(Sigma[i,i])<=1.0e-6:
    InvSig[i,i]=0.0
  else:
    InvSig[i,i]=1/Sigma[i,j]
print("\nInvSig=")
print(InvSig)

InvSig2=np.dot(InvSig,InvSig)
print("\nInvSig^2=")
print(InvSig2)
U=np.dot(Y,InvSig2)
U=np.dot(U,InvSig)
U=np.dot(U,np.transpose(X))

print("\nU=")
print(U)

Acur=np.dot(np.dot(C,U),R)
print("\nA_{CUR}=")
print(Acur)

[0.24210526 0.24210526 0.24210526 0.13684211 0.13684211]
[0.25263158 0.06315789 0.39473684 0.01578947 0.09473684 0.16842105
 0.01052632]
[4 1]
[1 2]
C=
[[5.7483457  0.        ]
 [2.87417285 0.        ]
 [7.18543212 0.        ]
 [1.43708642 0.        ]
 [0.         5.73451091]
 [0.         7.64601455]
 [0.         1.91150364]]
R=
[[5.62731434 5.62731434 5.62731434 0.         0.        ]
 [5.62731434 5.62731434 5.62731434 0.         0.        ]]
W=
[[4. 0.]
 [5. 0.]]

X=
[[-0.78086881 -0.62469505]
 [ 0.62469505 -0.78086881]]

Sigma=
[[ 0.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00 -6.40312424e+00]]

Y=
[[0. 1.]
 [1. 0.]]


InvSig=
[[ 0.          0.        ]
 [ 0.         -0.15617376]]

InvSig^2=
[[0.         0.        ]
 [0.         0.02439024]]

U=
[[0.00237954 0.00297442]
 [0.         0.        ]]

A_{CUR}=
[[0.17318842 0.17318842 0.17318842 0.         0.        ]
 [0.08659421 0.08659421 0.08659421 0.         0.        ]
 [0.21648552 0.21648552 0.21648552 0.         0.        ]
 [0

## CUR 함수화

In [6]:
import numpy as np
import numpy.linalg as nla
import numpy.random as nr

def cur(A,r=2):
  p=np.sum(A**2,axis=0)  # Frobenius norm을 이용한 확률
  q=np.sum(A**2,axis=1)
  p/=np.sum(p)
  q/=np.sum(q)

  col_list=nr.choice(np.array(range(len(p))),r,replace=False,p=p)
  row_list=nr.choice(np.array(range(len(q))),r,replace=False,p=q)

  # for ex 2-5 only
  col_list[0]=1
  col_list[1]=3
  row_list[0]=0
  row_list[1]=2

  C=np.zeros([A.shape[0],r],float)
  R=np.zeros([r,A.shape[1]],float)
  for i in range(r):
    C[:,i]=A[:,col_list[i]]
    C[:,i]/=((r*p[col_list[i]])**0.5)
    R[i,:]=A[row_list[i],:]
    R[i,:]/=((r*q[row_list[i]])**0.5)

  W=np.zeros([r,r],float)
  for i in range(r):
    for j in range(r):
      W[i,j]=A[row_list[i],col_list[j]]

  X,Sigma,Y=svd(W)

  #print(np.dot(np.dot(X,Sigma),np.transpose(Y)))
  InvSig=np.zeros_like(np.transpose(Sigma))
  for i in range(Sigma.shape[0]):
    if abs(Sigma[i,i])<=1.0e-6:
      InvSig[i,i]=0.0
    else:
      InvSig[i,i]=1/Sigma[i,j]

  InvSig2=np.dot(InvSig,InvSig)

  U=np.dot(Y,InvSig2)
  U=np.dot(U,InvSig)
  U=np.dot(U,np.transpose(X))

  return C,U,R

In [7]:
import numpy as np
import numpy.linalg as nla
import numpy.random as nr
A=np.array([[4,4,4,0,0],[2,2,2,0,0],[5,5,5,0,0],[1,1,1,0,0],[0,0,0,3,3],[0,0,0,4,4],[0,0,0,1,1]],float)

C,U,R=cur(A)
print("C=")
print(C)
print("\nR=")
print(R)
print("\nU=")
print(U)

C=
[[5.7483457  0.        ]
 [2.87417285 0.        ]
 [7.18543212 0.        ]
 [1.43708642 0.        ]
 [0.         5.73451091]
 [0.         7.64601455]
 [0.         1.91150364]]

R=
[[5.62731434 5.62731434 5.62731434 0.         0.        ]
 [5.62731434 5.62731434 5.62731434 0.         0.        ]]

U=
[[0.00237954 0.00297442]
 [0.         0.        ]]
